# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f49627ce727942e30e1eddd4a801fb82537c237a7d9f97c330ef8c72ef1baa71f4a5ce3e9b054c3ea22a30f22844a5ef0daab5c6ee830acf323b31954ed54e9

test:
  secret_key_base: a4ac4e76d811801ed9ce061ca70cdc18993161cfc05d7762c59210bfbf2b2df83e9547a890b5170be43ad36b02c645378678210200b311ac37226d635d0a2dec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
